name: Простая сборка

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Установить Java
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Собрать плагин
      run: mvn clean package
      
    - name: Сохранить результат
      uses: actions/upload-artifact@v4
      with:
        name: Плагин
        path: target/*.jar
